---
<<<<<<< HEAD
- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present
=======
- name: Install OpenJDK 21
  apt:
    name: openjdk-21-jdk
    state: present
>>>>>>> 5b3f8d9 (Completing ansible setup.)
